// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const {
  VITE_SUPABASE_URL,
  VITE_SUPABASE_PUBLISHABLE_KEY,
  REACT_APP_SUPABASE_URL,
  REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY,
} = import.meta.env;

const SUPABASE_URL = VITE_SUPABASE_URL || REACT_APP_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = VITE_SUPABASE_PUBLISHABLE_KEY || REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env file or GitHub Secrets.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
