// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const {
  VITE_SUPABASE_URL,
  VITE_SUPABASE_PUBLISHABLE_KEY,
  REACT_APP_SUPABASE_URL,
  REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY,
} = import.meta.env;

const SUPABASE_URL =
  VITE_SUPABASE_URL ||
  REACT_APP_SUPABASE_URL ||
  "https://rsmmmlmdwmvhuxipiwvz.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  VITE_SUPABASE_PUBLISHABLE_KEY ||
  REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbW1tbG1kd212aHV4aXBpd3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDMyNzMsImV4cCI6MjA3MzkxOTI3M30.f4z5Z4wpfoGlfQsiBUx_EvtWnSb4j-38WhQ_5xUiq1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
